apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: imagesearch
  POSTGRES_USER: admin

  REDIS_HOST: redis
  REDIS_PORT: "6379"
